name: Action para desplegar aplicaciones Java Spring Boot 2.5.12
description: 'Esta acción despliega aplicaciones Java Spring Boot 2.5.12'
inputs:
  app_name:
    description: 'Nombre de la aplicación a desplegar'
    required: true
  server_ip:
    description: 'Dirección IP del servidor donde se desplegará la aplicación'
    required: true
  remote_user:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
  tomcat_path:
    description: 'Ruta de instalación de Tomcat en el servidor remoto'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Desplegar aplicación Java Spring Boot 2.5.12
      run: |
        echo "Desplegando aplicación Java Spring Boot 2.5.12..."
        # Aquí iría el comando para desplegar la aplicación
        echo "Despliegue completado."
      shell: powershell
    # - name: Descargar artefactos
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: java-springboot-2.5.12
    - name: Subir artefacto al servidor remoto
      run: |
        echo "Subiendo artefacto al servidor remoto..."
        scp -r ./target/*.jar ./target/*.war '${ inputs.remote_user }'@'${ inputs.server_ip }':'${ inputs.tomcat_path }/webapps/'
        echo "Artefacto subido."
      shell: powershell
    - name: Desplegar en Tomcat
      run: |
        echo "Desplegando aplicación Java Spring Boot 2.5.12 en Tomcat..."
        move '${ inputs.tomcat_path }/webapps/${ inputs.app_name }.war' '${ inputs.tomcat_path }/webapps/${ inputs.app_name }.war.bak'
        echo "Despliegue en Tomcat completado."
      shell: powershell
    - name: Crear App Pool de IIS
      uses: ./.github/actions/utils/application-pool/create-app-pool
      with:
        app_pool_name: '${ inputs.app_name }-app-pool'
        managed_runtime_version: ''
        managed_pipeline_mode: 'Integrated'
        servidor_remoto: '${ inputs.server_ip }'
        usuario: '${ inputs.remote_user }'
    - name: Crear Sitio en IIS
      uses: ./.github/actions/utils/iis-site/create-iis-site
      with:
        site_name: '${ inputs.app_name }'
        app_pool_name: '${ inputs.app_name }-app-pool'
        physical_path: '${ inputs.tomcat_path }/webapps/${ inputs.app_name }'
        host_header: 'http'
        port: '80'
        servidor_remoto: '${ inputs.server_ip }'
        usuario: '${ inputs.remote_user }'
    - name: Configurar Reverse Proxy en IIS
      uses: ./.github/actions/utils/iis/configure-reverse-proxy
      with:
        site_name: '${ inputs.app_name }'
        servidor_remoto: '${ inputs.server_ip }'
        usuario: '${ inputs.remote_user }'