name: Action para desplegar aplicaciones Java Spring Boot 2.5.12
description: 'Esta acción despliega aplicaciones Java Spring Boot 2.5.12'
inputs:
  server_ip:
    description: 'Dirección IP del servidor donde se desplegará la aplicación'
    required: true
  remote_user:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
  tomcat_path:
    description: 'Ruta de instalación de Tomcat en el servidor remoto'
    required: true
  app_name:
    description: 'Nombre de la aplicación a desplegar'
    required: true
  version:
    description: 'Versión de la aplicación a desplegar'
    required: true
  extension:
    description: 'Extensión del artefacto a desplegar (ejemplo: war)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Desplegar en Tomcat
      run: |
        echo "Desplegando aplicación Java Spring Boot 2.5.12 en Tomcat..."
        try {
          ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} move \"C:\artifacts\java-springboot-2.5.12\${{ inputs.app_name }}.${{ inputs.extension }}\" \"${{ inputs.tomcat_path }}\webapps\"
        } catch {
          echo "Error al desplegar en Tomcat."
          exit 1
        }
        echo "Despliegue en Tomcat completado."
      shell: powershell
    - name: Crear App Pool de IIS
      uses: ./.github/actions/utils/application-pool/create-app-pool
      with:
        app_pool_name: '${{ inputs.app_name }}-app-pool'
        managed_runtime_version: ''
        managed_pipeline_mode: 'Integrated'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'
    - name: Crear Sitio en IIS
      uses: ./.github/actions/utils/iis-site/create-iis-site
      with:
        site_name: '${{ inputs.app_name }}'
        app_pool_name: '${{ inputs.app_name }}-app-pool'
        physical_path: '${{ inputs.tomcat_path }}/webapps/${{ inputs.app_name }}'
        host_header: 'http'
        port: '80'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'
    - name: Configurar Reverse Proxy en IIS
      uses: ./.github/actions/utils/iis/configure-reverse-proxy
      with:
        site_name: '${{ inputs.app_name }}'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'