name: Action para desplegar aplicaciones Node.js en IIS
description: Esta acción se encarga de desplegar aplicaciones Node.js en un servidor IIS.
inputs:
  server_ip:
    description: 'Dirección IP del servidor donde se desplegará la aplicación'
    required: true
  remote_user:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
  app_name:
    description: 'Nombre de la aplicación'
    required: true
  project_path:
    description: 'Ruta de la aplicación en el servidor'
    required: true
  start_command:
    description: 'Comando para iniciar la aplicación con PM2'
    required: true
  app_port:
    description: 'Puerto de la aplicación'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Desplegar aplicación en IIS
      run: |
        echo "Instalar dependencias npm..."
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} "cd C:\artifacts\nodejs\${{ inputs.app_name }} && npm install"
        echo "Eliminar proceso pm2..."
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} pm2 stop ${{ inputs.app_name }}
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} pm2 delete ${{ inputs.app_name }}
        echo "Eliminando directorio de la aplicación..."
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} rmdir /s /q \"${{ inputs.project_path }}\${{ inputs.app_name }}\"
        echo "Desplegando aplicación en IIS..."
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} move \"C:\artifacts\nodejs\${{ inputs.app_name }}\" \"${{ inputs.project_path }}\"
      shell: cmd

    - name: Crear App Pool de IIS
      uses: ./orquestador/.github/actions/utils/application-pool/create-app-pool
      with:
        app_pool_name: '${{ inputs.app_name }}-app-pool'
        managed_runtime_version: 'v4.0'
        managed_pipeline_mode: 'Integrated'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'

    - name: Conceder permisos al directorio del proyecto
      run: |
        echo "Concediendo permisos al directorio del proyecto en el servidor remoto"
        ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} powershell -Command "icacls '${{ inputs.project_path }}\${{ inputs.app_name }}' /grant 'IIS_IUSRS:(OI)(CI)M'"
      shell: powershell

    - name: Crear Sitio en IIS
      uses: ./orquestador/.github/actions/utils/iis-site/create-iis-site
      with:
        site_name: '${{ inputs.app_name }}'
        app_pool_name: '${{ inputs.app_name }}-app-pool'
        physical_path: '${{ inputs.project_path }}\${{ inputs.app_name }}'
        host_header: 'localhost'
        port: '80'
        # ip_address: '${{ inputs.ip_address }}'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'

    - name: Iniciar aplicación con PM2
      run: |
        echo "Parametros:"
        echo "  - Nombre de la aplicación: ${{ inputs.app_name }}"
        echo "  - Ruta del proyecto: ${{ inputs.project_path }}\${{ inputs.app_name }}"
        echo "  - Comando de inicio: ${{ inputs.start_command }}"
        echo "  - Ruta completa: ${{ inputs.project_path }}\${{ inputs.app_name }}\${{ inputs.start_command }}"
        echo "Iniciando aplicación..."
        # Si la variable start_command es igual a "-", entonces iniciamos con pm2 serve
        if ("${{ inputs.start_command }}" -eq "-") {
          ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} "pm2 serve ${{ inputs.project_path }}\${{ inputs.app_name }}\build ${{ inputs.app_port }} --name ${{ inputs.app_name }}"
        } else {
          ssh ${{ inputs.remote_user }}@${{ inputs.server_ip }} "$env:PORT = ${{ inputs.app_port }} && $env:NODE_PORT = ${{ inputs.app_port }} && pm2 start ${{ inputs.project_path }}\${{ inputs.app_name }}\${{ inputs.start_command }} --name ${{ inputs.app_name }}"
        }
      shell: powershell

    - name: Configurar proxy inverso en IIS
      uses: ./orquestador/.github/actions/utils/iis-site/setup-reverse-proxy
      with:
        site_name: '${{ inputs.app_name }}'
        target_url: 'http://localhost:${{ inputs.app_port }}'
        servidor_remoto: '${{ inputs.server_ip }}'
        usuario: '${{ inputs.remote_user }}'
