name: Crear App Pool de IIS
description: 'Esta acción crea un Application Pool en IIS'
inputs:
  app_pool_name:
    description: 'Nombre del Application Pool a crear'
    required: true
  managed_runtime_version:
    description: 'Versión de .NET Framework para el Application Pool'
    required: true
    default: 'v4.0'
  managed_pipeline_mode:
    description: 'Modo de canalización administrada para el Application Pool'
    required: true
    default: 'Integrated'
  servidor_remoto:
    description: 'Nombre o dirección IP del servidor remoto donde se creará el Application Pool'
    required: true
  usuario:
    description: 'Usuario para conectarse al servidor remoto'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Ver parámetros de entrada
      run: |
        echo "Creando App Pool de IIS con los siguientes parámetros:"
        echo "Nombre del App Pool: ${{ inputs.app_pool_name }}"
        echo "Versión de .NET: ${{ inputs.managed_runtime_version }}"
        echo "Modo de canalización: ${{ inputs.managed_pipeline_mode }}"
      shell: powershell
    - name: Crear App Pool
      run: |
        echo "Creando App Pool de IIS con los siguientes parámetros:"
        echo "Nombre del App Pool: ${{ inputs.app_pool_name }}"
        echo "Versión de .NET: ${{ inputs.managed_runtime_version }}"
        echo "Modo de canalización: ${{ inputs.managed_pipeline_mode }}"
      shell: powershell
    - name: Crear App Pool
      run: |
        echo "Creando App Pool de IIS..."
        
        # Cargar el contenido del script PowerShell desde archivo
        $scriptPath = ".\create-app-pool.ps1"
        if (Test-Path $scriptPath) {
          $scriptContent = Get-Content -Path $scriptPath -Raw
          
          # Crear un wrapper que incluye el script y los parámetros
          $wrapperScript = @"
          # Script original
          $scriptContent

          # Llamar a la función principal con parámetros
          try {
            `$result = & { $scriptContent } -appPoolName '${{ inputs.app_pool_name }}' -managedRuntimeVersion '${{ inputs.managed_runtime_version }}' -managedPipelineMode '${{ inputs.managed_pipeline_mode }}'
            Write-Host "Script ejecutado exitosamente"
          } catch {
            Write-Host "Error ejecutando script: `$_"
            exit 1
          }
          "@
          
          # Codificar en base64
          $encodedScript = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($wrapperScript))
          
          # Ejecutar remotamente
          ssh ${{ inputs.usuario }}@${{ inputs.servidor_remoto }} "powershell -EncodedCommand $encodedScript"
          
          if ($LASTEXITCODE -eq 0) {
            echo "App Pool de IIS creado exitosamente."
          } else {
            echo "Error al crear App Pool de IIS."
            exit 1
          }
        } else {
          echo "Error: No se encontró el archivo $scriptPath"
          exit 1
        }
      shell: powershell
      working-directory: ./orquestador/.github/actions/utils/application-pool/create-app-pool