name: Crear Sitio IIS
description: Crea un sitio IIS con la configuración especificada.
inputs:
  site_name:
    description: "Nombre del sitio IIS"
    required: true
  app_pool_name:
    description: "Nombre del Application Pool asociado al sitio"
    required: true
  physical_path:
    description: "Ruta física del sitio (ejemplo: C:\\inetpub\\wwwroot\\mysite)"
    required: true
  host_header:
    description: "Encabezado del sitio (ejemplo: http, https)"
    required: true
  port:
    description: "Puerto en el que se escuchará el sitio (ejemplo: 80)"
    required: true
  servidor_remoto:
    description: "Nombre o dirección IP del servidor remoto donde se creará el sitio"
    required: true
  usuario:
    description: "Usuario para conectarse al servidor remoto"
    required: true
runs:
  using: "composite"
  steps:
    - name: Crear Sitio IIS en servidor remoto
      shell: powershell
      run: |
        echo "Creando Sitio IIS '${{ inputs.site_name }}'..."
        
        # Cargar el contenido del script PowerShell desde archivo
        $scriptPath = ".\create-iis-site.ps1"
        if (Test-Path $scriptPath) {
          $scriptContent = Get-Content -Path $scriptPath -Raw
          
          # Codificar en base64 para ejecución remota
          $encodedScript = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($scriptContent))
          
          # Parámetros para el script
          $arguments = "-siteName '${{ inputs.site_name }}' -appPoolName '${{ inputs.app_pool_name }}' -sitePath '${{ inputs.physical_path }}' -hostHeader '${{ inputs.host_header }}' -port ${{ inputs.port }}"
          
          # Ejecutar remotamente
          ssh ${{ inputs.usuario }}@${{ inputs.servidor_remoto }} "powershell -EncodedCommand $encodedScript $arguments"
          
          if ($LASTEXITCODE -eq 0) {
            echo "Sitio IIS '${{ inputs.site_name }}' creado exitosamente."
          } else {
            echo "Error al crear Sitio IIS."
            exit 1
          }
        } else {
          echo "Error: No se encontró el archivo $scriptPath"
          exit 1
        }
      working-directory: ./orquestador/.github/actions/utils/iis-site/create-iis-site