name: Configurar Reverse Proxy en IIS
description: Configura un sitio de Reverse Proxy en IIS para redirigir tráfico a un servidor backend.
inputs:
  site_name:
    description: "Nombre del sitio IIS"
    required: true
  target_url:
    description: "URL del servidor backend (ejemplo: http://localhost:5000)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Configurar Reverse Proxy
      shell: pwsh
      run: |
        ./.github/actions/utils/iis-site/setup-reverse-proxy/setup-reverse-proxy.ps1 -siteName '${{ inputs.site_name }}' -targetUrl '${{ inputs.target_url }}'
      working-directory: ./orquestador/.github/actions/utils/iis-site/setup-reverse-proxy