name: Code Analysis
description: Run static code analysis
inputs:
  SONAR_TOKEN:
    description: 'SonarQube token'
    required: true
  SONAR_HOST_URL:
    description: 'SonarQube server URL'
    required: true
runs:
  using: "composite"
  steps:
    - name: Escaneo SonarQube para proyectos no compilados
      working-directory: ./app
      shell: cmd
      run: |
        echo "Iniciando escaneo de SonarQube..."
        sonar-scanner -Dsonar.projectKey=${{ github.event.repository.name }} -Dsonar.sources=. -Dsonar.host.url=${{ inputs.SONAR_HOST_URL }} -Dsonar.login=${{ inputs.SONAR_TOKEN }}