name: Orquestador de despliegue de aplicaciones
on:
  workflow_call:
    inputs:
      rama:
        description: 'Rama a desplegar - Permite saber si desplegaremos en producción (rama main) o en desarrollo (rama develop)'
        required: true
        type: string
      tecnologia:
        description: 'Tecnología a desplegar'
        required: true
        type: string
      requiere_compilar:
        description: 'Indica si se requiere compilación'
        required: true
        type: boolean
      despliegue_en:
        description: 'Entorno de despliegue'
        required: true
        type: string
    secrets:
      server_ip:
        description: 'Dirección IP del servidor donde se desplegará la aplicación'
        required: true
      remote_user:
        description: 'Usuario para conectarse al servidor remoto'
        required: true
      tomcat_path:
        description: 'Ruta de instalación de Tomcat en el servidor remoto'
        required: true

jobs:
  build:
    runs-on: self-hosted
    if: ${{ inputs.requiere_compilar == 'true' }}
    outputs:
      app_name: ${{ steps.build.outputs.app_name }}
      version: ${{ steps.build.outputs.version }}
      extension: ${{ steps.build.outputs.extension }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Información del entorno a compilar
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
      - name: Build
        uses: ./.github/actions/build/${{ inputs.tecnologia }}
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}

  test:
    runs-on: self-hosted
    if: ${{ inputs.requiere_compilar == 'true' }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Información del entorno a testear
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
      - name: test
        uses: ./.github/actions/test/${{ inputs.tecnologia }}

  deploy:
    runs-on: self-hosted
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Información del entorno a desplegar
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
          echo "Despliegue en: ${{ inputs.despliegue_en }}"
      - name: Deploy Java Spring Boot 2.5.12
        if: ${{ inputs.tecnologia == 'java-springboot-2.5.12' }}
        uses: ./.github/actions/deploy/${{ inputs.tecnologia }}
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}
          tomcat_path: ${{ secrets.TOMCAT_PATH }}
          app_name: ${{ needs.build.outputs.app_name }}
          version: ${{ needs.build.outputs.version }}
          extension: ${{ needs.build.outputs.extension }}
