name: Orquestador de despliegue de aplicaciones
on:
  workflow_call:
    inputs:
      rama:
        description: 'Rama a desplegar - Permite saber si desplegaremos en producción (rama main) o en desarrollo (rama develop)'
        required: true
        type: string
      tecnologia:
        description: 'Tecnología a desplegar'
        required: true
        type: string
      requiere_compilar:
        description: 'Indica si se requiere compilación'
        required: true
        type: boolean
      despliegue_en:
        description: 'Entorno de despliegue'
        required: true
        type: string
    secrets:
      server_ip:
        description: 'Dirección IP del servidor donde se desplegará la aplicación'
        required: true
      remote_user:
        description: 'Usuario para conectarse al servidor remoto'
        required: true
      tomcat_path:
        description: 'Ruta de instalación de Tomcat en el servidor remoto'
        required: false
      project_path:
        description: 'Ruta del proyecto en el servidor remoto'
        required: false

jobs:
  build:
    runs-on: self-hosted
    if: inputs.requiere_compilar
    outputs:
      app_name: ${{ steps.build_step_java.outputs.app_name || steps.build_step_net_framework.outputs.app_name }}
      version: ${{ steps.build_step_java.outputs.version || steps.build_step_net_framework.outputs.version }}
      extension: ${{ steps.build_step_java.outputs.extension || steps.build_step_net_framework.outputs.extension }}
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4
        with:
          path: app
      - name: Checkout orquestador repository
        uses: actions/checkout@v4
        with:
          repository: jgallardo-clever/test-orquestador-fge
          path: orquestador
      - name: Información del entorno a compilar
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
      - name: Build Java Spring Boot 2.5.12
        id: build_step_java
        if: ${{ inputs.tecnologia == 'java-springboot-2.5.12' }}
        uses: ./orquestador/.github/actions/build/java-springboot-2.5.12
        with:
          server_ip: ${{ secrets.server_ip }}
          remote_user: ${{ secrets.remote_user }}

      - name: Tomar outputs de la build Java Spring Boot 2.5.12
        if: ${{ inputs.tecnologia == 'java-springboot-2.5.12' }}
        run: |
          echo "Nombre de la aplicación: ${{ steps.build_step_java.outputs.app_name }}"
          echo "Versión de la aplicación: ${{ steps.build_step_java.outputs.version }}"
          echo "Extensión del artefacto: ${{ steps.build_step_java.outputs.extension }}"

      - name: Build .NET Framework
        id: build_step_net_framework
        if: ${{ inputs.tecnologia == 'net-framework' }}
        uses: ./orquestador/.github/actions/build/net-framework
        with:
          server_ip: ${{ secrets.server_ip }}
          remote_user: ${{ secrets.remote_user }}

      - name: Tomar outputs de la build .NET Framework
        if: ${{ inputs.tecnologia == 'net-framework' }}
        run: |
          echo "Nombre de la aplicación: ${{ steps.build_step_net_framework.outputs.app_name }}"

      - name: Build PHP Laravel
        id: build_step_php_laravel
        if: ${{ inputs.tecnologia == 'php-laravel' }}
        uses: ./orquestador/.github/actions/build/php-laravel
        with:
          server_ip: ${{ secrets.server_ip }}
          remote_user: ${{ secrets.remote_user }}
          app_key: ${{ secrets.app_key }}
          app_url: ${{ secrets.app_url }}

      - name: Tomar outputs de la build PHP Laravel
        if: ${{ inputs.tecnologia == 'php-laravel' }}
        run: |
          echo "Nombre de la aplicación: ${{ steps.build_step_php_laravel.outputs.app_name }}"

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Información del entorno a testear
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
      # - name: Test Java Spring Boot 2.5.12
      #   if: ${{ inputs.tecnologia == 'java-springboot-2.5.12' }}
      #   uses: ./.github/actions/test/java-springboot-2.5.12

  deploy:
    runs-on: self-hosted
    needs: [build, test]
    steps:
      - name: Checkout orquestador repository
        uses: actions/checkout@v4
        with:
          repository: jgallardo-clever/test-orquestador-fge
          path: orquestador
      - name: Información del entorno a desplegar
        run: |
          echo "Rama: ${{ inputs.rama }}"
          echo "Tecnología: ${{ inputs.tecnologia }}"
          echo "Despliegue en: ${{ inputs.despliegue_en }}"
      - name: Deploy Java Spring Boot 2.5.12
        if: ${{ inputs.tecnologia == 'java-springboot-2.5.12' }}
        uses: ./orquestador/.github/actions/deploy/java-springboot-2.5.12
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}
          tomcat_path: ${{ secrets.TOMCAT_PATH }}
          app_name: ${{ needs.build.outputs.app_name }}
          version: ${{ needs.build.outputs.version }}
          extension: ${{ needs.build.outputs.extension }}
          ip_address: 'localhost'

      - name: Deploy .NET Framework
        if: ${{ inputs.tecnologia == 'net-framework' }}
        uses: ./orquestador/.github/actions/deploy/net-framework
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.REMOTE_USER }}
          project_path: '${{ secrets.PROJECT_PATH }}'
          app_name: ${{ needs.build.outputs.app_name }}
          ip_address: 'localhost'