name: Disparador de orquestador
on:
  workflow_dispatch:
    inputs:
      rama:
        description: 'Rama del repositorio'
        required: true
        type: choice
        options:
          - 'main'
          - 'develop'
      tecnologia:
        description: 'Tecnología a utilizar'
        required: true
        type: choice
        options:
          - 'java-springboot-2.5.12'
          - 'net-framework'
          - 'php-laravel'
          - 'nodejs'
          - 'kubernetes'
      tipo_despliegue:
        description: 'Tipo de despliegue'
        required: true
        type: choice
        options:
          - 'site'
          - 'webapp'

jobs:
  run-orquestador:
    uses: jgallardo-clever/test-orquestador-fge/.github/workflows/orquestador.yml@main
    with:
      rama: ${{ inputs.rama }}
      tecnologia: ${{ inputs.tecnologia }}
      tipo_despliegue: ${{ inputs.tipo_despliegue }}
      # despliegue_en: ${{ inputs.despliegue_en }}
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    secrets: inherit